In [1]:
 !pip3 install -r /content/requirements.txt
 !pip3 install bitsandbytes

In [2]:
from transformers import (pipeline, AutoTokenizer, AutoModelForCausalLM)
from transformers.modeling_outputs import CausalLMOutputWithPast
from torch import Tensor
import torch
import torch.nn.functional as F
from tools import tensor_rank_positions, rank_difference, n_smaller, z_score
from watermark_tools_context_independent import (
    generate_soft_greenlist_watermark_context_independent, watermark_checker, predict_greenlist_confidence, smoothed_logits
)

import os
import transformers
from huggingface_hub import login
import bitsandbytes as bnb
import numpy as np

In [3]:
def load_model(model_id: str):
    # Set Hugging Face Hub token
    hf_token = "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"

    # Manually login with the token
    login(token=hf_token)

    if os.path.exists(model_id):
        local_dir = "./" + model_id
        tokenizer = AutoTokenizer.from_pretrained(local_dir)
        model = AutoModelForCausalLM.from_pretrained(local_dir, device_map="auto", load_in_8bit=True)
        return model, tokenizer
    else:
        print(f"Model {model_id} not found locally. Downloading and caching/...")
        tokenizer = AutoTokenizer.from_pretrained(model_id)
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="auto",
            load_in_8bit=True,
        )
        model.save_pretrained(model_id)
        tokenizer.save_pretrained(model_id)
        return model, tokenizer

In [4]:
ranks_small = torch.load('ranks_small.pt')
ranks_large = torch.load('ranks_big.pt')

<ipython-input-4-9d8467c9f439>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ranks_small = torch.load('ranks_small.pt')
<ipython-input-4-9d8467c9f439>:2: FutureWarning: Y

In [5]:
print(ranks_small.shape)
print(ranks_large.shape)

torch.Size([30, 32000])
torch.Size([30, 32000])


In [6]:
rank_diff = rank_difference(ranks_large, ranks_small)
print(rank_diff)

confidence = predict_greenlist_confidence(ranks_large, ranks_small)
print(confidence)
print(torch.max(confidence))
print(torch.min(confidence))

tensor([[ 5310,    -9, 21309,  ...,   -25,   -25,   -25],
        [ 5310,    -9,    -9,  ...,   -25,   -25,   -25],
        [ 5307,   -10, 21323,  ...,   -25,   -25,   -25],
        ...,
        [ 5297,   -16,   -16,  ...,   -31,   -31,   -31],
        [ 5299,   -14,   -14,  ...,   -29,   -29,   -29],
        [  -26,   -13,   -13,  ...,   -24,   -24,   -24]])
tensor([0.8911, 0.6821, 0.8130,  ..., 0.4856, 0.4856, 0.4856],
       dtype=torch.float16)
tensor(0.9971, dtype=torch.float16)
tensor(0.0005, dtype=torch.float16)


In [7]:
torch.save(rank_diff, 'rank_diff.pt')
torch.save(confidence, 'confidence.pt')

In [8]:
large_unclean = torch.load('logits_big.pt')
small_unclean = torch.load('logits_small.pt')
logits_large = torch.stack([large_unclean[i][0] for i in range(len(large_unclean))])
logits_small = torch.stack([small_unclean[i][0] for i in range(len(small_unclean))])

<ipython-input-8-b54ae3309da7>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  large_unclean = torch.load('logits_big.pt')
<ipython-input-8-b54ae3309da7>:2: FutureWarning: 

In [9]:
print(logits_large)
print(logits_small)

tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        ...,
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf]])
tensor([[  -inf,   -inf, 6.6953,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf, 8.1016,  ...,   -inf,   -inf,   -inf],
        ...,
        [  -inf,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf,   -inf,  ...,   -inf,   -inf,   -inf]])


In [10]:
smoothed_logits = smoothed_logits(confidence, logits_large, logits_small)
torch.save(smoothed_logits, 'smoothed_logits.pt')

In [11]:
print(smoothed_logits)
print(smoothed_logits.shape)

tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        ...,
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf]])
torch.Size([30, 32000])


In [12]:
# Load the tokenizer and model for LLaMA 3.1 (use the appropriate model ID)
# model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"
model_id = "meta-llama/Llama-2-7b-hf"
# tokenizer = AutoTokenizer.from_pretrained(model_id)
# model = AutoModelForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map="auto")
model, tokenizer = load_model(model_id)
LLAMA_VOCAB_SIZE = tokenizer.vocab_size
print(LLAMA_VOCAB_SIZE)

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /root/.cache/huggingface/token
Login successful


The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
/usr/local/lib/python3.10/dist-packages/transformers/quantizers/auto.py:174: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.
  warnings.warn(warning_msg)


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

32000


In [31]:
# Set pad token (instruct models usually use the same eos token as pad token)
tokenizer.pad_token_id = tokenizer.eos_token_id

# Prepare the input
inputs = tokenizer(["The president of the United States of America in 2022 is"], return_tensors="pt")

# Generate tokens using Greedy Search and retrieve the scores for each generated token
outputs = model.generate(**inputs, max_new_tokens=30, return_dict_in_generate=True, output_scores=True)
print(outputs.scores[0].shape)
print(outputs.scores[1].shape)
print(len(outputs.scores))
print(smoothed_logits.shape)
outputs.scores = tuple(logit.unsqueeze(0) for logit in smoothed_logits)
print(outputs.scores[0].shape)
print(len(outputs.scores))



# print(outputs.scores)
# scores = list(outputs.scores)
# for i in range(30):
#     scores[i] = smoothed_logits[]
# outputs.scores = tuple(scores)


# Calculate the transition scores (logits to probabilities) for each generated token
transition_scores = model.compute_transition_scores(
    outputs.sequences, outputs.scores, normalize_logits=True
)

# Calculate the input length (relevant for decoder-only models like LLaMA)
input_length = 1 if model.config.is_encoder_decoder else inputs.input_ids.shape[1]

# Extract the generated tokens after the input prompt
generated_tokens = outputs.sequences[:, input_length:]

transition_scores = torch.nan_to_num(transition_scores, nan=0.0)


# Print the model output
print(tokenizer.decode(generated_tokens[0]))

# Print the generated tokens and their transition scores (converted to probabilities)
for tok, score in zip(generated_tokens[0], transition_scores[0]):
    token = tokenizer.decode(tok)  # Decode token id back to string
    print(f"Generated token: {token}, Probability score: {np.exp(score.item())}")

torch.Size([1, 32000])
torch.Size([1, 32000])
30
torch.Size([30, 32000])
torch.Size([1, 32000])
30
Joe Biden.
The president of the United States of America in 2023 will be Joe Biden.
The president of the
Generated token: Joe, Probability score: 1.0
Generated token: B, Probability score: 1.0
Generated token: iden, Probability score: 1.0
Generated token: ., Probability score: 1.0
Generated token: 
, Probability score: 0.9767447274866707
Generated token: The, Probability score: 0.0
Generated token: president, Probability score: 1.1766785635032432e-06
Generated token: of, Probability score: 1.0
Generated token: the, Probability score: 1.0
Generated token: United, Probability score: 1.0
Generated token: States, Probability score: 1.0
Generated token: of, Probability score: 1.0
Generated token: America, Probability score: 1.0
Generated token: in, Probability score: 1.0
Generated token: , Probability score: 1.0
Generated token: 2, Probability score: 1.0
Generated token: 0, Probability score: 

In [25]:
watermark = torch.load('/content/watermark.pt')

<ipython-input-25-0d6d1714dacf>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  watermark = torch.load('/content/watermark.pt')


In [26]:
print(f'watermark shape = {watermark.shape}')
print(f'generated shape = {generated_tokens.shape}')

watermark shape = torch.Size([32000])
generated shape = torch.Size([1, 30])


In [27]:
value = watermark_checker(watermark, generated_tokens[0], 0.7)

In [28]:
print(value)

0.6


In [29]:
torch.inf - torch.inf

nan