In [1]:
 !pip3 install -r /content/requirements.txt
 !pip3 install bitsandbytes

In [15]:
from transformers import (pipeline, AutoTokenizer, AutoModelForCausalLM)
from transformers.modeling_outputs import CausalLMOutputWithPast
from torch import Tensor
import torch
import torch.nn.functional as F
from tools import tensor_rank_positions, rank_difference, n_smaller, z_score
from watermark_tools_context_independent import (
    generate_soft_greenlist_watermark_context_independent, watermark_checker, predict_greenlist_confidence, smoothed_logits
)

import os
import transformers
from huggingface_hub import login
import bitsandbytes as bnb
import numpy as np

In [3]:
def load_model(model_id: str):
    # Set Hugging Face Hub token
    hf_token = "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"

    # Manually login with the token
    login(token=hf_token)

    if os.path.exists(model_id):
        local_dir = "./" + model_id
        tokenizer = AutoTokenizer.from_pretrained(local_dir)
        model = AutoModelForCausalLM.from_pretrained(local_dir, device_map="auto", load_in_8bit=True)
        return model, tokenizer
    else:
        print(f"Model {model_id} not found locally. Downloading and caching/...")
        tokenizer = AutoTokenizer.from_pretrained(model_id)
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="auto",
            load_in_8bit=True,
        )
        model.save_pretrained(model_id)
        tokenizer.save_pretrained(model_id)
        return model, tokenizer

In [5]:
ranks_small = torch.load('ranks_small.pt')
ranks_large = torch.load('ranks_big.pt')

<ipython-input-5-9d8467c9f439>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ranks_small = torch.load('ranks_small.pt')
<ipython-input-5-9d8467c9f439>:2: FutureWarning: Y

In [6]:
print(ranks_small.shape)
print(ranks_large.shape)

torch.Size([30, 32000])
torch.Size([30, 32000])


In [7]:
rank_diff = rank_difference(ranks_large, ranks_small)
print(rank_diff)

confidence = predict_greenlist_confidence(ranks_large, ranks_small)
print(confidence)
print(torch.max(confidence))
print(torch.min(confidence))

tensor([[ 5314,    -8, 21325,  ...,   -23,   -23,   -23],
        [ 5301,   -14,   -14,  ...,   -28,   -28,   -28],
        [ 5301,   -14,   -14,  ...,   -29,   -29,   -29],
        ...,
        [  -26,   -13, 21325,  ...,   -29,   -29,   -29],
        [  -28,   -15, 21299,  ...,   -29,   -29,   -29],
        [ 5301,   -13, 21325,  ...,   -27,   -27,   -27]])
tensor([0.7754, 0.6890, 0.8013,  ..., 0.4954, 0.4954, 0.4954],
       dtype=torch.float16)
tensor(0.9971, dtype=torch.float16)
tensor(0.0006, dtype=torch.float16)


In [8]:
torch.save(rank_diff, 'rank_diff.pt')
torch.save(confidence, 'confidence.pt')

In [19]:
large_unclean = torch.load('logits_big.pt')
small_unclean = torch.load('logits_small.pt')
logits_large = torch.stack([large_unclean[i][0] for i in range(len(large_unclean))])
logits_small = torch.stack([small_unclean[i][0] for i in range(len(small_unclean))])

<ipython-input-19-b54ae3309da7>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  large_unclean = torch.load('logits_big.pt')
<ipython-input-19-b54ae3309da7>:2: FutureWarning

In [20]:
print(logits_large)
print(logits_small)

tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        ...,
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf]])
tensor([[  -inf,   -inf, 9.2500,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
        ...,
        [  -inf,   -inf, 8.6719,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf, 7.1367,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf, 8.7266,  ...,   -inf,   -inf,   -inf]])


In [21]:
smoothed_logits = smoothed_logits(confidence, logits_large, logits_small)
torch.save(smoothed_logits, 'smoothed_logits.pt')

In [22]:
print(smoothed_logits)
print(smoothed_logits.shape)

tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        ...,
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf]])
torch.Size([30, 32000])
