In [ ]:
 !pip3 install -r /content/requirements.txt
 !pip3 install bitsandbytes

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.5/417.5 kB 18.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 13.6 MB/s eta 0:00:00
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.3
    Uninstalling urllib3-2.2.3:
      Successfully uninstalled urllib3-2.2.3
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface-hub 0.24.7
    Uninstalling huggingface-hub-0.24.7:
      Successfully uninstalled huggingface-hub-0.24.7
  Using cached bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl.metadata (3.5 kB)
Using cached bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl (122.4 MB)


In [ ]:
from transformers import (pipeline, AutoTokenizer, AutoModelForCausalLM)
from transformers.modeling_outputs import CausalLMOutputWithPast
from torch import Tensor
import torch
import torch.nn.functional as F
from tools import tensor_rank_positions, rank_difference, n_smaller, z_score
from watermark_tools_context_independent import (
    generate_soft_greenlist_watermark_context_independent, watermark_checker, predict_greenlist_confidence, smoothed_logits
)

import os
import transformers
from huggingface_hub import login
import bitsandbytes as bnb
import numpy as np

In [ ]:
def load_model(model_id: str):
    # Set Hugging Face Hub token
    hf_token = "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"

    # Manually login with the token
    login(token=hf_token)

    if os.path.exists(model_id):
        local_dir = "./" + model_id
        tokenizer = AutoTokenizer.from_pretrained(local_dir)
        model = AutoModelForCausalLM.from_pretrained(local_dir, device_map="auto", load_in_8bit=True)
        return model, tokenizer
    else:
        print(f"Model {model_id} not found locally. Downloading and caching/...")
        tokenizer = AutoTokenizer.from_pretrained(model_id)
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="auto",
            load_in_8bit=True,
        )
        model.save_pretrained(model_id)
        tokenizer.save_pretrained(model_id)
        return model, tokenizer

In [ ]:
ranks_small = torch.load('ranks_small.pt')
ranks_large = torch.load('ranks_big.pt')

<ipython-input-4-9d8467c9f439>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ranks_small = torch.load('ranks_small.pt')
<ipython-input-4-9d8467c9f439>:2: FutureWarning: Y

In [ ]:
print(ranks_small.shape)
print(ranks_large.shape)

torch.Size([30, 32000])
torch.Size([30, 32000])


In [ ]:
rank_diff = rank_difference(ranks_large, ranks_small)
print(rank_diff)

confidence = predict_greenlist_confidence(ranks_large, ranks_small)
print(confidence)
print(torch.max(confidence))
print(torch.min(confidence))

tensor([[ 5314,    -8, 21325,  ...,   -23,   -23,   -23],
        [ 5301,   -14,   -14,  ...,   -28,   -28,   -28],
        [ 5301,   -14,   -14,  ...,   -29,   -29,   -29],
        ...,
        [  -26,   -13, 21325,  ...,   -29,   -29,   -29],
        [  -28,   -15, 21299,  ...,   -29,   -29,   -29],
        [ 5301,   -13, 21325,  ...,   -27,   -27,   -27]])
tensor([0.7754, 0.6890, 0.8013,  ..., 0.4954, 0.4954, 0.4954],
       dtype=torch.float16)
tensor(0.9971, dtype=torch.float16)
tensor(0.0006, dtype=torch.float16)


In [ ]:
torch.save(rank_diff, 'rank_diff.pt')
torch.save(confidence, 'confidence.pt')

In [ ]:
large_unclean = torch.load('logits_big.pt')
small_unclean = torch.load('logits_small.pt')
logits_large = torch.stack([large_unclean[i][0] for i in range(len(large_unclean))])
logits_small = torch.stack([small_unclean[i][0] for i in range(len(small_unclean))])

<ipython-input-8-b54ae3309da7>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  large_unclean = torch.load('logits_big.pt')
<ipython-input-8-b54ae3309da7>:2: FutureWarning: 

In [ ]:
print(logits_large)
print(logits_small)

tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        ...,
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf]])
tensor([[  -inf,   -inf, 9.2500,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
        ...,
        [  -inf,   -inf, 8.6719,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf, 7.1367,  ...,   -inf,   -inf,   -inf],
        [  -inf,   -inf, 8.7266,  ...,   -inf,   -inf,   -inf]])


In [ ]:
smoothed_logits = smoothed_logits(confidence, logits_large, logits_small)
torch.save(smoothed_logits, 'smoothed_logits.pt')

In [ ]:
print(smoothed_logits)
print(smoothed_logits.shape)

tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        ...,
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
        [-inf, -inf, -inf,  ..., -inf, -inf, -inf]])
torch.Size([30, 32000])


In [ ]:
# Load the tokenizer and model for LLaMA 3.1 (use the appropriate model ID)
# model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"
model_id = "meta-llama/Llama-2-7b-hf"
# tokenizer = AutoTokenizer.from_pretrained(model_id)
# model = AutoModelForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map="auto")
model, tokenizer = load_model(model_id)
LLAMA_VOCAB_SIZE = tokenizer.vocab_size
print(LLAMA_VOCAB_SIZE)

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /root/.cache/huggingface/token
Login successful
Model meta-llama/Llama-2-7b-hf not found locally. Downloading and caching/...


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/609 [00:00<?, ?B/s]

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.


model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

32000


In [ ]:
# Set pad token (instruct models usually use the same eos token as pad token)
tokenizer.pad_token_id = tokenizer.eos_token_id

# Prepare the input
inputs = tokenizer(["Who is the current president of the USA? The current president of the United States of America is"], return_tensors="pt")

# Generate tokens using Greedy Search and retrieve the scores for each generated token
outputs = model.generate(**inputs, max_new_tokens=30, return_dict_in_generate=True, output_scores=True)
print(outputs.scores[0].shape)
print(outputs.scores[1].shape)
print(len(outputs.scores))
print(smoothed_logits.shape)
outputs.scores = tuple(logit.unsqueeze(0) for logit in smoothed_logits)
print(outputs.scores[0].shape)
print(len(outputs.scores))



# print(outputs.scores)
# scores = list(outputs.scores)
# for i in range(30):
#     scores[i] = smoothed_logits[]
# outputs.scores = tuple(scores)


# Calculate the transition scores (logits to probabilities) for each generated token
transition_scores = model.compute_transition_scores(
    outputs.sequences, outputs.scores, normalize_logits=True
)

# Calculate the input length (relevant for decoder-only models like LLaMA)
input_length = 1 if model.config.is_encoder_decoder else inputs.input_ids.shape[1]

# Extract the generated tokens after the input prompt
generated_tokens = outputs.sequences[:, input_length:]

# Print the model output
print(tokenizer.decode(generated_tokens[0]))

# Print the generated tokens and their transition scores (converted to probabilities)
for tok, score in zip(generated_tokens[0], transition_scores[0]):
    token = tokenizer.decode(tok)  # Decode token id back to string
    print(f"Generated token: {token}, Probability score: {np.exp(score.item())}")

torch.Size([1, 32000])
torch.Size([1, 32000])
30
torch.Size([30, 32000])
torch.Size([1, 32000])
30
Donald Trump.
Who is the current president of the USA?
Who is the current president of the USA? The current president of the United States
Generated token: Donald, Probability score: 0.0
Generated token: Trump, Probability score: nan
Generated token: ., Probability score: 0.0
Generated token: 
, Probability score: 0.0
Generated token: Who, Probability score: nan
Generated token: is, Probability score: nan
Generated token: the, Probability score: nan
Generated token: current, Probability score: nan
Generated token: president, Probability score: 0.0
Generated token: of, Probability score: 0.0
Generated token: the, Probability score: nan
Generated token: USA, Probability score: 0.0
Generated token: ?, Probability score: 0.0
Generated token: 
, Probability score: 0.0
Generated token: Who, Probability score: 0.0
Generated token: is, Probability score: nan
Generated token: the, Probability scor