In [1]:
 !pip3 install -r /content/requirements.txt
 !pip3 install bitsandbytes

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.5/417.5 kB 21.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 10.5 MB/s eta 0:00:00
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.3
    Uninstalling urllib3-2.2.3:
      Successfully uninstalled urllib3-2.2.3
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface-hub 0.24.7
    Uninstalling huggingface-hub-0.24.7:
      Successfully uninstalled huggingface-hub-0.24.7
  Using cached bitsandbytes-0.44.0-py3-none-manylinux_2_24_x86_64.whl.metadata (3.5 kB)
Using cached bitsandbytes-0.44.0-py3-none-manylinux_2_24_x86_64.whl (122.4 MB)


In [2]:
from transformers import (pipeline, AutoTokenizer, AutoModelForCausalLM)
from transformers.modeling_outputs import CausalLMOutputWithPast
from torch import Tensor
import torch
import torch.nn.functional as F
from tools import tensor_rank_positions, rank_difference, n_smaller, z_score
from watermark_tools_context_independent import (
    generate_soft_greenlist_watermark_context_independent, watermark_checker, predict_greenlist_confidence
)

import os
import transformers
from huggingface_hub import login
import bitsandbytes as bnb
import numpy as np

In [3]:
def load_model(model_id: str):
    # Set Hugging Face Hub token
    hf_token = "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"

    # Manually login with the token
    login(token=hf_token)

    if os.path.exists(model_id):
        local_dir = "./" + model_id
        tokenizer = AutoTokenizer.from_pretrained(local_dir)
        model = AutoModelForCausalLM.from_pretrained(local_dir, device_map="auto", load_in_8bit=True)
        return model, tokenizer
    else:
        print(f"Model {model_id} not found locally. Downloading and caching/...")
        tokenizer = AutoTokenizer.from_pretrained(model_id)
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="auto",
            load_in_8bit=True,
        )
        model.save_pretrained(model_id)
        tokenizer.save_pretrained(model_id)
        return model, tokenizer

In [4]:
torch.cuda.empty_cache()

In [5]:
!nvidia-smi

Mon Sep 30 00:57:21 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [6]:
# Load the tokenizer and model for TinyLLaMA 1.1B
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
# tokenizer = AutoTokenizer.from_pretrained(model_id)
# model = AutoModelForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map="auto")
model, tokenizer = load_model(model_id)
LLAMA_VOCAB_SIZE = tokenizer.vocab_size
print(LLAMA_VOCAB_SIZE)

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /root/.cache/huggingface/token
Login successful
Model TinyLlama/TinyLlama-1.1B-Chat-v1.0 not found locally. Downloading and caching/...


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.


model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

32000


In [7]:
# Set pad token (instruct models usually use the same eos token as pad token)
tokenizer.pad_token_id = tokenizer.eos_token_id

# Prepare the input
inputs = tokenizer(["Who is the current president of the USA? The current president of the United States of America "], return_tensors="pt")

# Generate tokens using Greedy Search and retrieve the scores for each generated token
outputs = model.generate(**inputs, max_new_tokens=30, return_dict_in_generate=True, output_scores=True, do_sample=True)

# Calculate the transition scores (logits to probabilities) for each generated token
transition_scores = model.compute_transition_scores(
    outputs.sequences, outputs.scores, normalize_logits=True
)

# Calculate the input length (relevant for decoder-only models like LLaMA)
input_length = 1 if model.config.is_encoder_decoder else inputs.input_ids.shape[1]

# Extract the generated tokens after the input prompt
generated_tokens = outputs.sequences[:, input_length:]

# Print the model output
print(tokenizer.decode(generated_tokens[0]))

# Print the generated tokens and their transition scores (converted to probabilities)
for tok, score in zip(generated_tokens[0], transition_scores[0]):
    token = tokenizer.decode(tok)  # Decode token id back to string
    print(f"Generated token: {token}, Probability score: {np.exp(score.item())}")

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1885: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(


is 
- (Optional) Who is the current Prime Minister of Canada and what is their name? The current Prime Minister of Canada is Justin Tru
Generated token: is, Probability score: 0.04745571237020648
Generated token: , Probability score: 0.032378113969779784
Generated token: 
, Probability score: 0.10518667080198639
Generated token: -, Probability score: 0.15988913616379805
Generated token: (, Probability score: 0.01319721769459965
Generated token: Optional, Probability score: 0.0689491320524618
Generated token: ), Probability score: 0.9189306230962576
Generated token: Who, Probability score: 0.11016272164265037
Generated token: is, Probability score: 0.4490386008180912
Generated token: the, Probability score: 0.9524339805870728
Generated token: current, Probability score: 0.3565767930163519
Generated token: Prime, Probability score: 0.21686780653321922
Generated token: Minister, Probability score: 0.9924093520519645
Generated token: of, Probability score: 0.9707592135777562
Generated toke

In [8]:
# Save the rankings of each token from the large model into a text file
ranks = torch.stack([tensor_rank_positions(outputs.scores[i][0]) for i in range(30)]) # Stack tensors into a single tensor
print(ranks)
torch.save(ranks, 'ranks_small.pt')
torch.save(outputs.scores, 'logits_small.pt')

tensor([[26671, 21351,    17,  ..., 10684, 10683, 10682],
        [26684, 21357, 21356,  ..., 10689, 10688, 10687],
        [26684, 21357, 21356,  ..., 10690, 10689, 10688],
        ...,
        [26686, 21358,    19,  ..., 10691, 10690, 10689],
        [26687, 21359,    44,  ..., 10690, 10689, 10688],
        [26684, 21357,    18,  ..., 10688, 10687, 10686]])


In [9]:
print(torch.load('ranks_small.pt'))
print(torch.load('logits_small.pt'))

tensor([[26671, 21351,    17,  ..., 10684, 10683, 10682],
        [26684, 21357, 21356,  ..., 10689, 10688, 10687],
        [26684, 21357, 21356,  ..., 10690, 10689, 10688],
        ...,
        [26686, 21358,    19,  ..., 10691, 10690, 10689],
        [26687, 21359,    44,  ..., 10690, 10689, 10688],
        [26684, 21357,    18,  ..., 10688, 10687, 10686]])
(tensor([[  -inf,   -inf, 9.2500,  ...,   -inf,   -inf,   -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[   -inf,    -inf, 11.3516,  ...,    -inf,    -inf,    -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf

<ipython-input-9-f8b37d5fe31c>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  print(torch.load('ranks_small.pt'))
<ipython-input-9-f8b37d5fe31c>:2: FutureWarning: You are 